### ISSUE TITLE
Allow entering Gun Store without a License

### ISSUE THREAD

**Issue by Kagemd** [broke-protocol/issues#268]
So this was an idea from another user but I thought about it and I think it would be worth suggesting.

You should allow users to enter the Gun Store without a License. However, if they do not have said License they would be committing a 3 star crime.

**Comment by TENTACLEBOSS** [comment]
The issue here is people don't really have much of a reason to care about stars. People would happily take the stars and rush the store and steal a gun, and they'll do it again and again just to get the guns and kill people because they want to be criminals. They don't care if they get arrested or if a cop shoots them. 

This would allow players to completely bypass the license system, licenses would now only punish legitimate players, and incentivize players to just steal the guns because it's faster to do so, which would make the gun shop just as open to abuse as it is prior to 0.7.0. It would render gun licenses completely obsolete.

**Comment by Kagemd** [comment]
Yeah I rethought the suggestion.

To "T" off the the original suggestion would be to make NPC Police more aggressive.

**Comment by TENTACLEBOSS** [comment]
I still feel like that wouldn't be enough. Even if they get more aggressive, people are still negating the licenses. At that point you may as well not have the licenses.

**Comment by LightVelox** [comment]
if you enter the gunstore without a gun license the owner should shoot you, that would prevent people from just killing anyone that enter the store and preventing anyone in the server to stop them

**Comment by BrokeProtocol** [comment]
Getting a wanted level for just entering a store makes no sense realistically.
