### ISSUE TITLE
Election vote for new mayors

### ISSUE THREAD

**Issue by TENTACLEBOSS** [broke-protocol/issues#269]
Right now the system of obtaining the mayoral position is highly exploitable. Once the mayor is arrested for self-defense, or dies, or leaves the server, it's first come first serve for the job, which opens up a very powerful role to morons who either don't understand the role, or want to abuse it. 

However the potential for a random griefer to take the role could be mitigated with a small election vote system that gives all players in the server a chance to vote for a willing candidate, electing new mayors via a simple democratic process. Here is how the system could work: 

- When the mayor role becomes available, players have a two minute window to "Apply for the job."
- After this time, a server-wide vote occurs, where players can press a corresponding button to vote "Yes" for a mayoral candidate of choice, who had previously applied for the role. 
- The candidate who gets the most votes is elected as mayor. 

This system would minimize the chances of idiots taking the role of mayor, and instead keep it in the hands of candidates desired by a majority of the server, increasing the likelihood of suitable players taking the role, as opposed to rewarding it to randoms who harass, kill, and arrest the previous mayor.

**Comment by Vixonary** [comment]
I agree. If this idea doesn't work, at least let us have an option to throw out a Mayor that is abusing the power, since vote kick doesn't work.

**Comment by Vixonary** [comment]
So far after spending at least 2 hours on the test server, I found most non-english people are constantly denying Licenses for their own sake and only giving it to their friends for benefits. They'll also disconnect as the mayor so the friend may take over the role and abuse it as well. We need to do something about it and fast.

**Comment by BrokeProtocol** [comment]
Voting a Mayor in or out: https://github.com/DeathByKorea/BrokeProtocol/issues/288

**Comment by BrokeProtocol** [comment]
Voting in a Mayor
====
Instead of paying $80 to become the mayor, it should be handled by requesting the job and then a voting screen pops up on all online players screen to either accept or deny the person who is requesting to become Mayor.

There would need to be a cooldown in between how often a player can request the job because it could be used as a tool to troll and spam everyone on the server. If someone doesn't pick, their vote will automatically default to accept.

Voting out a Mayor
====
Vice versa to voting in Mayors, anyone should be able to vote a Mayor out by talking to the NPC Mayor and selecting "Kick current Mayor out", the vote will be silent and not pop up on every-ones screen, but it will save the request from each player. Also, there should be modifiers to effect the total number of current votes, such as if the current Mayor has committed crimes in the past 10 minutes, it will increase the likelihood of the current Mayor getting kicked from office with lessor people(making it so you do not need entire server for a vote to pass), also if Mayor is afk there could be a modifier for that too.

If someone selects to vote out the current Mayor they can revert their request by hitting the same button again.

Final Comments
====
This voting idea should help keep people from just taking the job and giving themselves all the licenses without any care on actually doing the job as Mayor.
