### ISSUE TITLE
Disallow the use of weapons in Townhall

### ISSUE THREAD

**Issue by Rafe123PL** [broke-protocol/issues#270]
No possibility of using a weapon in the Town hall, because it is a place of security. This will facilitate Mayor's work and give one safe place in the game.

**Comment by TENTACLEBOSS** [comment]
The issue is other players who aren't the mayor would treat it like a safe-space, hiding there in the middle of fights etc. Could be exploitable. 

Perhaps guns could be screened at the door by ai security and temporarily removed until a player leaves the town hall again. The mayor could also allow people to bypass the screening to let their personal guards enter the premises with weapons. This might be a better system than just outright preventing all weapon usage.

**Comment by Rafe123PL** [comment]
an even better idea.

**Comment by Kasup2** [comment]
It could also be a thing where entering the townhall without "giving" the gun away while inside could get a nice 5 stars and a team of ai cops spawn outside the townhall

**Comment by TENTACLEBOSS** [comment]
I mentioned it in another thread but while that's a cool idea in concept, right now the cops are easily evade-able as they shoot like morons. I'd maybe be more on board with that idea if cops proposed a threat.

**Comment by MereGamer** [comment]
In that case, that we can not use in the gun shop either
