### ISSUE TITLE
Suicide Cooldown Timer

### ISSUE THREAD

**Issue by BrokeProtocol** [broke-protocol/issues#280]
In response to NongBenz thinking about removing the suicide button completely, don't! In some situations if a player has been handcuffed randomly and left, or if has been knocked out and no one has come to them for 10+ minutes, it would be bad to have no suicide button at all, however adding a cooldown timer before you can use on these events would be a better alternative then completely removing it.

- Add a cooldown timer for suiciding (1-5 Minutes)
- Apply the suicide timer for the following:
  - While knocked out, this will allow paramedic players to have some time to respond and perhaps roleplay a bit.
  - While handcuffed/restrained, lot of people abuse the suicide button to get out of being arrested.
  - While in prison, people tend to suicide often in Jail due to extremely long jail sentencing time, 
  - While having wanted level, there is a exploit I'm not sure everyone knows about, but if you steal a ton load of stuff, then stash it in a chest then suicide, you basically get everything free without any penalties.

This cooldown timer will need balancing in other aspects of the game, such as with the Police Officer, and how crimes work. 

Here is some good suggestions regarding handcuffing and suicide: https://github.com/DeathByKorea/BrokeProtocol/issues/171

Also for while knocked out, add bleedout timer: https://github.com/DeathByKorea/BrokeProtocol/issues/93

**Comment by TENTACLEBOSS** [comment]
Yeah outright removing it would be far too harsh and exploitable. A timer in prison that matches the timer that they have to wait would be perfect, because then prison might actually mean something, AND it would also give a purpose to breaking people out. 

The only problem in that case is it wouldn't stop fresh players who just want to RDM from just making another account. But hopefully the licensing system will stop those people with a few adjustments anyway.
