### ISSUE TITLE
You do not lose ammo after death if it's apart of job (Police)

### ISSUE THREAD

**Issue by BrokeProtocol** [broke-protocol/issues#283]
At this point not really sure if this was intended to be a thing because it has existed forever, but basically cops shouldn't be allowed to keep all their pistol/taser ammo and handcuffs after dying, this is one major reason why criminals tend to pick the police job.  Instead, when respawning, give: 1 tazer + 1 round, 1 handcuff, plus 1 baton and a limited amount pistol ammo(10 to 20). Respawning and getting job for first time equipment should be different in what you get.

Same thing happened when Gang members used to have shotguns and uzi's, they would keep their weapons plus all their ammo they have collected in previous life.

edit: added pistol ammo amount suggestion

**Comment by LightVelox** [comment]
cops are not overpowered as they used to be, remove the ammo that they/you/me keep and it will simply destroy all server, let me give a example:
A actually good player(good aim,driving skills) go to the gunshop and steal all weapons, he kill all player cops(bots are laughable,not even counting them), now all cop players have only pistols to use since they can't get inside the gunshop because they will get killed, even with a pistol with 999+ ammo it's hard as shit to kill these guys with assault rifles and shit, imagine if you lost all ammo after death? all servers would turn to a complete riot,the last time it happened in the official server it took like 4 hours to put the players in jail

**Comment by BrokeProtocol** [comment]
Only lose the ammo you collected, as a cop you could still spawn with like 10-20 rounds, or another small amount. Criminals or people who RDM take the police job mainly to never lose handcuffs, tazer rounds, or pistol ammo, and it's the best job out of any of the other jobs due to this fact. You can hoard infinite amount of ammo/handcuffs through death, it's broken. This is a small tweak among many others that is needed to balance out police and rdm'ing a like.

**Comment by LightVelox** [comment]
still, 10-20 rounds it not enough even to kill a single npc at +10-feet distance, imagine a skilled player, sure the cop abuse is a very big problem, but players being able to do anything they want because no other player can stop them will simply break the game, in the official server it's already a shit when someone takes the riot set+shotgun, imagine if you had only 10-20 ammo, it should have some type of protection, like if you steal the bombs at the airport you lose your job instantly, same for robbing the bank or killing a certain amount of innocent people
