### ISSUE TITLE
Bleed out timer when knocked out

### ISSUE THREAD

**Issue by BrokeProtocol** [broke-protocol/issues#93]
2 minutes until medics can revive you before death.

**Comment by DarkRosanne** [comment]
Completly on board with this idea, 2 minutes gives enough time for people to get there but not too long that your just sitting there for ages. Also along with this, I think you should make it that if someone gets knocked out or something, You cannot suicide straight away along with this timer, maybe make it after a minute you can suicide, but you still have another minute to be revived.
For general people killing themselves to avoid things like combat, arrest and such. Make it so that if your arrested you cannot suicide? and maybe have a combat tick thing which games like Dayz implimented (You get hit you cannot suicide for a certain ammount of time) or something along that line.
